name: 'build'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_rtmidi_natives:
    name: 'build on ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
      with:
        submodules: true
    - name: apt update (on Linux)
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        echo y | sudo apt-get install doxygen cmake ninja-build libasound2-dev libjack-jackd2-dev
    - name: build on Unix-y OS
      if: matrix.os != 'windows-latest'
      run: |
        cd external/rtmidi
        mkdir build
        cmake -S . -B build
        cmake --build build
        cd ../..
    - name: upload artifact - Ubuntu
      if: success() && matrix.os == 'ubuntu-20.04'
      uses: actions/upload-artifact@v2
      with:
        name: rtmidi-lib-linux
        path: external/rtmidi/build/librtmidi.so
    - name: upload artifact - macOS
      if: success() && matrix.os == 'macos-10.15'
      uses: actions/upload-artifact@v2
      with:
        name: rtmidi-lib-macos
        path: |
          external/rtmidi/build/librtmidi.dylib
    - name: build on Windows
      if: success() && matrix.os == 'windows-latest'
      run: |
        cd external\rtmidi
        mkdir build
        cmake -S . -B build
        cmake --build build
        cd ..\..
    - name: upload artifact - Windows
      if: success() && matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: rtmidi-lib-windows
        path: external\rtmidi\build\Debug\rtmidi.*

  build_jar:
    name: 'build Jar'
    needs: build_rtmidi_natives
    runs-on: 'ubuntu-20.04'
    steps:
    - name: checkout # it's duplicate, but it's too annoying to split build steps just to avoid it
      uses: actions/checkout@v2.3.4
      with:
        submodules: true
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: download artifacts - Linux
      uses: actions/download-artifact@v2
      with:
        name: rtmidi-lib-linux
    - name: download artifacts - Mac
      uses: actions/download-artifact@v2
      with:
        name: rtmidi-lib-macos
    - name: download artifacts - Windows
      uses: actions/download-artifact@v2
      with:
        name: rtmidi-lib-windows
    - name: relocate artifacts
      run:
        mv ./librtmidi.so ./librtmidi.dylib ./rtmidi.dll ./rtmidi.pdb rtmidi-jna/
    - name: build jar
      run:
         ./gradlew --warning-mode all build
    - name: upload artifact - Jar
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: rtmidi-jna-jars
        path: rtmidi-jna/build/libs/*.jar
